# -*- coding: utf-8 -*-
# .readthedocs.yml

build:
  image: latest

python:
  version: 3.6
  setup_py_install: true


#Too slow -> impossible to build -> use requirements_file
#conda:
#  file: environment.yml

requirements_file: docs/source/requirements_docs.txt
