# Config file for automatic building at travis-ci.org

language: python
sudo: false

python:
    - 3.6

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/xraysloth
    - export PATH="$HOME/xraysloth/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a

install:
    - conda create -q -n sloth python=$TRAVIS_PYTHON_VERSION
    - source activate sloth
    - conda install pip
    - pip install -r requirements.txt
    - pip install -r requirements_docs.txt
    - pip install .

script:
  - cd docs && make html

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  on:
    branch: master
  github-token: $GITHUB_TOKEN
  local-dir: docs/build/html
  committer-from-gh: true
