python:
    - '3.6'
branches:
    only:
        - master
node_js: 6
install:
    - pip install -U pip
    - pip install -r requirements.txt
    - pip install -r requirements_docs.txt
    - pip install -e .
#script:
#   - python -m unittest
after_success:
  - cd docs && make html
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  on:
    branch: master
  github-token: $GITHUB_TOKEN
  local-dir: docs/build/html
  committer-from-gh: true
