#Python environment for: https://github.com/maurov/xraysloth
#conda env create -f environment.yml
name: sloth-env
channels:
  - defaults
dependencies:
  - python=3.6
  - pip=10.0.1
  - spyder
  - conda-forge::xraylib
  - GSECARS::xraylarch>=0.9.40
  - pip:
    - hdf5plugin
    - fisx>=1.1.6
    - silx>=0.9.0
    - PyMca5>=5.4.0