#Python environment for: https://github.com/maurov/xraysloth
#Target: basic usage as user
#Usage: conda env create -f environment.yml
name: sloth-env
channels:
  - defaults
dependencies:
  - python=3.6
  - git=2.11
  - pip=10.0.1
  - spyder
  - conda-forge::xraylib
  - GSECARS::xraylarch>=0.9.40
  - pip:
    - hdf5plugin
    - fisx>=1.1.6
    - fabio>=0.8.0
    - silx>=0.9.0
    - PyMca5>=5.4.0
    - http://ftp.esrf.eu/pub/scisoft/shadow3/wheels/shadow3-18.5.30-cp36-cp36m-linux_x86_64.whl