#Python environment for: https://github.com/maurov/xraysloth
#Target: for running on mybinder.org
#Usage: conda env create -f environment.yml
name: sloth-binder
channels:
    - defaults
    #NOTE: specific channels are given per-package, not here!
dependencies:
    - python=3.6
    - pip
    - nodejs
    - numpy>=1.16
    - scipy>=1.2.0
    - matplotlib>=2.0
    - h5py>=2.7
    - pyyaml
    - conda-forge::ipywidgets
    - conda-forge::ipympl
    - conda-forge::widgetsnbextension
    - conda-forge::jupyterlab
    - conda-forge::xraylib
    - conda-forge::lmfit>=0.9.13
    - pip:
        - jupyterlab_server
        - jupyterlab-git
        - silx>=0.10.1
        - http://ftp.esrf.eu/pub/scisoft/shadow3/wheels/shadow3-18.5.30-cp36-cp36m-linux_x86_64.whl; sys_platform == 'linux'
        - git+https://github.com/maurov/xraysloth
