#Python environment for: https://github.com/maurov/xraysloth
#Target: for running a local Jupyterlab instance + separate code editing
#Usage: conda env create -f environment.yml
name: sloth-lab
channels:
    - defaults
    #NOTE: specific channels are given per-package, not here!
dependencies:
    - python=3.6
    - pip
    - nodejs
    - numpy>=1.16
    - scipy>=1.2.0
    - matplotlib>=2.0
    - h5py>=2.8
    - sphinx>=1.5
    - sphinxcontrib
    - pyyaml
    - termcolor
    - sqlalchemy>=0.9
    - conda-forge::ipywidgets
    - conda-forge::ipympl
    - conda-forge::widgetsnbextension
    - conda-forge::jupyterlab
    - conda-forge::nbsphinx
    - conda-forge::xraylib
    - conda-forge::peakutils>=1.0.0
    - conda-forge::asteval>=0.9.12
    - conda-forge::uncertainties>=3.0.3
    - conda-forge::lmfit>=0.9.13
    - GSECARS::pyshortcuts>=1.3
    - GSECARS::wxmplot
    - GSECARS::wxutils
    # - conda-forge::rise
    - pip:
        #: IDE tools
        - jedi
        - rope
        - autopep8
        - yapf
        - flake8
        - black
        #: Linters
        - pylint
        - pycodestyle
        - pydocstyle
        #: Build docs
        - sphinxcontrib-napoleon
        - sphinx_rtd_theme
        - recommonmark
        #: JupyterLab extensions
        #- nb_black
        #- jupyterlab_code_formatter
        - jupyterlab_server
        - jupyterlab-git
        #- jupyterlab_latex
        #: Base libs
        - hdf5plugin
        - silx>=0.11
        - http://ftp.esrf.eu/pub/scisoft/shadow3/wheels/shadow3-18.5.30-cp36-cp36m-linux_x86_64.whl; sys_platform == 'linux'

#: -> run 'postBuild' script to complete install
