#Python DEVELOPMENT environment for: https://github.com/maurov/xraysloth
#Target: developing `silx` and `larch` (with wxPython)
#Usage: conda env create -f environment-dev.yml
name: sloth-dev
channels:
  - defaults
  #NOTE: specific channels are given per-package, not here!
dependencies:
  #Basics
  - python=3.6
  - git=2.11        #as Debian9
  - pip>=19.0.2     #18.1 fails!
  - cython>0.21.1
  #- pyopengl=3.1.1a1
  #- anaconda:pyopengl-accelerate=3.1.1a1 #numpy 1.9!
  #- conda-forge::pyopencl
  - six>=1.10
  - qt>=5.7
  - pyqt=5
  - wxpython>=4.0.3
  - numpy>=1.16
  - scipy>=1.2.0
  - matplotlib>=2.0
  - qtconsole
  - pillow>=3.4
  #Utils
  - pyzmq
  - pytz
  - termcolor
  - nose
  - swig
  - dill
  - pyparsing
  - sphinx
  - sphinxcontrib
  - conda-forge::nbsphinx
  - reportlab
  - natsort
  #- spyder #not used anymore
  - python-dateutil
  - h5py>=2.7
  - mako
  - setuptools
  - wheel
  - pyyaml
  - pandas
  - scikit-learn>=0.18
  - scikit-image
  - dask>=1.0.0
  - sqlalchemy>=0.9
  - traitlets
  - requests>=2.1
  - bottlechest
  - conda-forge::pyinstaller
  #Jupyter project
  - ipython
  - ipykernel
  - jupyter
  - ipywidgets
  - conda-forge::ipympl
  - conda-forge::widgetsnbextension
  - conda-forge::jupyterlab
  #Scisoft
  - conda-forge::xraylib
  - conda-forge::ase
  #Larch & friends
  - patchelf #required in xraylarch: setup.py(fix_linux_dylibs)
  - conda-forge::peakutils>=1.0.0
  - conda-forge::lmfit>=0.9.12
  - conda-forge::asteval>=0.9.12
  - conda-forge::psutil
  - conda-forge::pytest
  - conda-forge::uncertainties>=3.0
  - conda-forge::pycifrw
  - GSECARS::wxmplot>=0.9.33
  - GSECARS::wxutils>=0.2.3
  - GSECARS::pyshortcuts>=1.3
  #NeXpy
  - nexpy::nexusformat
  - nexpy::nexpy
  #Orange3
  #- conda-forge::orange3 #*conflicts with OASYS1* /:test:`orange-canvas -l 4`
  ### PIP ###
  - pip:
    - hdf5plugin
    - spec2nexus
    - fisx>=1.1.6
    - fabio>=0.8.0
    - palettable
    #Shadow & OASYS
    - resources
    - http://ftp.esrf.eu/pub/scisoft/shadow3/wheels/shadow3-18.5.30-cp36-cp36m-linux_x86_64.whl; sys_platform == 'linux'
    - oasys-canvas-core
    - oasys-widget-core
    - oasys1
    - srxraylib
    - syned
    - wofry
    #- git+https://github.com/oasys-kit/wofryshadow.git
    #- git+https://github.com/oasys-kit/ShadowOui.git    
    - OASYS1-ShadowOui
    - OASYS1-XOPPY
    #- OASYS1-XRayServer
    #- OASYS1-SRW
  ### MANUALLY BUILT FROM SOURCE =DEVEL (KEEP ORDER) ###
  #silx>=0.9.0       #maurov's fork-> pip install .
  #PyMca5>=5.4.0     #maurov's fork-> pip install .
  #xraylarch>=0.9.41 #maurov's fork-> python setup.py build/install