#conda env create -f environment.yml
name: sloth-env
channels:
  - defaults
  - conda-forge
dependencies:
  - qt
  - pyqt=5
  #- wxpython
  - python=3.6
  - numpy
  - scipy
  - matplotlib
  - pillow
  - six
  - bottlechest
  - ipython
  - ipykernel
  - jupyter
  - ipywidgets
  - pyzmq
  - pandas
  - pyyaml
  - h5py
  - pytz
  - python-dateutil
  - requests
  - termcolor
  - nose
  - swig
  - dill
  - scikit-learn
  - pyparsing
  - sqlalchemy
  - sphinx
  - sphinxcontrib
  #conda-forge
  - xraylib
  - silx
  #- ase
  - peakutils
  - lmfit
  - asteval
  - psutil
  - pytest
  - uncertainties
  - pip:
    - PyCifRW
    - hdf5plugin
    #- fisx
    #- PyMca5
    #- fabio
    #- pyFAI
    - http://ftp.esrf.eu/pub/scisoft/shadow3/wheels/shadow3-18.5.30-cp36-cp36m-linux_x86_64.whl