#Python environment for: https://github.com/maurov/xraysloth
#Target: basic usage as user
#Usage: conda env create -f environment.yml
name: sloth-orange
channels:
  - defaults
dependencies:
  - python=3.6
  - git=2.11
  - pip=10.0.1
  - conda-forge::orange3
  - pip:
    - hdf5plugin
    - fisx>=1.1.6
    - fabio>=0.8.0
    - silx>=0.9.0
    - PyMca5>=5.4.0
    - git+https://gitlab.esrf.fr/silx/silx-addon.git