#Python environment for: https://github.com/maurov/xraysloth
#Target: basic usage as user (larch from GSECARS, silx with pip)
#Usage: conda env create -f environment.yml
name: sloth-env
channels:
  - defaults
dependencies:
  - python=3.6
  - git=2.11    #as Debian9
  - pip=10.0.1  #18.1 fails!	
  - qt>=5.7
  - pyqt=5
  - wxpython=4.0.3
  - numpy>=1.10
  - scipy>=0.17
  - matplotlib>=2.0
  - h5py>=2.7
  - sqlalchemy>=0.9
  - scikit-learn>=0.18
  - ipython
  - ipykernel<5
  - jupyter
  - ipywidgets
  - spyder
  - conda-forge::xraylib
  - conda-forge::peakutils>=1.0.0
  - conda-forge::lmfit>=0.9.12
  - conda-forge::asteval>=0.9.12
  - conda-forge::uncertainties>=3.0
  - conda-forge::pycifrw
  - GSECARS::wxmplot>=0.9.32
  - GSECARS::wxutils>=0.2
  - GSECARS::xraylarch
  - nexpy::nexusformat
  - nexpy::nexpy
  - pip:
    - hdf5plugin
    - spec2nexus
    - fisx>=1.1.6
    - fabio>=0.8.0
    - silx>=0.9.0
    - PyMca5>=5.4.0
    - http://ftp.esrf.eu/pub/scisoft/shadow3/wheels/shadow3-18.5.30-cp36-cp36m-linux_x86_64.whl