#Python environment for: https://github.com/maurov/xraysloth
#Target: minimal environment for OASYS
#Usage: conda env create -f environment-oasys.yml
name: oasys-env
channels:
  - defaults
dependencies:
  - python=3.6
  - git=2.11    #as Debian9
  - pip=10.0.1  #18.1 fails!
  - qt>=5.7
  - pyqt=5
  - numpy>=1.10
  - scipy>=0.17
  - matplotlib>=2.0
  - h5py>=2.7
  - requests
  - conda-forge::xraylib
  - pip:
    - hdf5plugin
    - spec2nexus
    - fisx>=1.1.6
    - fabio>=0.8.0
    - silx>=0.9.0
    - PyMca5>=5.4.0
    - http://ftp.esrf.eu/pub/scisoft/shadow3/wheels/shadow3-18.5.30-cp36-cp36m-linux_x86_64.whl
    - oasys-canvas-core
    - oasys-widget-core
    - oasys1
    - srxraylib
    - syned
    - wofry
    - pySRU
    - git+https://github.com/oasys-kit/wofryshadow.git
    - git+https://github.com/oasys-kit/ShadowOui.git