#Python DEVELOPMENT environment for: https://github.com/maurov/xraysloth
#Target: developing `silx` and `larch` (NO WX)
#Usage: conda env create -f environment-dev.yml
name: sloth-dev
channels:
  - defaults
  #NOTE: specific channels are given per-package, not here!
dependencies:
  - python=3.6
  - git=2.11        #Debian9
  - pip=10.0.1
  - cython>0.21.1
  - pyopengl>=3.1.1a1
  - anaconda:pyopengl-accelerate>=3.1.1a1
  - qt>=5.7
  - pyqt=5
  #- wxpython>=4.0.3
  - numpy>=1.10
  - six>=1.10
  - scipy>=0.17
  - matplotlib>=2.0
  - qtconsole
  - pillow>=3.4
  - python-dateutil
  - h5py>=2.7
  - mako
  - setuptools
  - wheel
  - pyyaml
  - pandas
  - scikit-learn>=0.18
  - scikit-image
  - sqlalchemy>=0.9
  - traitlets
  - requests>=2.1
  - bottlechest
  - ipython
  - ipykernel
  - jupyter
  - ipywidgets
  - ipympl
  - pyzmq
  - pytz
  - termcolor
  - nose
  - swig
  - dill
  - pyparsing
  - sphinx
  - sphinxcontrib
  - reportlab
  - natsort
  - spyder
  - patchelf #required in xraylarch: setup.py(fix_linux_dylibs)
  ### CONDA-FORGE ###
  - conda-forge::pyopencl
  - conda-forge::nbsphinx
  - conda-forge::pyinstaller
  - conda-forge::xraylib
  - conda-forge::ase
  - conda-forge::peakutils>=1.0.0
  - conda-forge::lmfit>=0.9.12
  - conda-forge::asteval>=0.9.12
  - conda-forge::psutil
  - conda-forge::pytest
  - conda-forge::uncertainties>=3.0
  - conda-forge::pycifrw
  #- conda-forge::orange3 #*conflicts with OASYS1* /:test:`orange-canvas -l 4`
  ###
  #- GSECARS::wxmplot>=0.9.30 #IF WX
  #- GSECARS::wxutils         #IF WX
  - GSECARS::pyshortcuts>=1.3
  ###
  - nexpy::nexusformat
  - nexpy::nexpy
  ### PIP ###
  - pip:
    - hdf5plugin
    - spec2nexus
    - fisx>=1.1.6
    - fabio>=0.8.0
    - palettable
    #- oasys-canvas-core  #OASYS kit 
    #- oasys-widget-core  #OASYS kit 
    #- oasys1		  #OASYS kit 
    #- srxraylib	  #OASYS kit 
    #- syned		  #OASYS kit 
    #- wofry		  #OASYS kit 
    ### PIP WHEELS ###
    - http://ftp.esrf.eu/pub/scisoft/shadow3/wheels/shadow3-18.5.30-cp36-cp36m-linux_x86_64.whl
  ### BUILD FROM SOURCE =DEVEL (KEEP ORDER) ###
  #silx>=0.9.0       #git fetch upstream; git merge upstream/master; pip install .
  #PyMca5>=5.4.0     #git fetch upstream; git merge upstream/master; pip install .
  #xraylarch>=0.9.40 #git fetch upstream; git merge upstream/master; python setup.py build/install