# -*- coding: utf-8 -*-
# Conda environment configuration for: https://github.com/maurov/xraysloth
# Target: *FULL* environment for sloth based on
#   +> Larch (Wx)
#   +> SILX  (PyQt5)
#   +> OASYS
#   +> Jupyter
#   +> GL/CL
#   +> XRT
#   +> Nexus
#   +> Dev tools
# NOTE: first install packages in apt.txt
# Usage: mamba/conda env create -f environment.yml
name: sloth
channels:
    - defaults
dependencies:
    - python == 3.8
    - pip
    - nodejs
    - wxpython >= 4.0.4  # still not working with pip!
    - pyqt >= 5.9
    - conda-forge::pyqtwebengine
    - qtconsole
    - h5py == 2.10
    - numpy >= 1.12
    - scipy >= 1.2
    - pandas >= 0.25
    - matplotlib >= 3.0
    - lmfit >= 1.0.2
    - requests
    - pyyaml
    - psutil
    - termcolor
    - pytools
    - palettable
    - openpyxl
    - conda-forge::pint
    - esrf-bcu::ptpython >= 3.0.16
    - conda-forge::silx >= 0.15.0
    - conda-forge::pymca >= 5.6.5
    - conda-forge::xraydb >= 4.4
    - conda-forge::xraylib
    - rtree  # -> `requirements-xrt.txt` (pip fails for some unknown reason)
    #- conda-forge:dask        # for xarray (in requirements-jupyter.txt)
    #- conda-forge:netCDF4     # for xarray (in requirements-jupyter.txt)
    #- conda-forge:bottleneck  # for xarray (in requirements-jupyter.txt)
    - pip:
        #- -r ../requirements.txt        #: base // INSTALLED HERE VIA CONDA!!!
        - -r requirements-dev.txt       #: IDE/dev tools
        - -r requirements-docs.txt      #: to build docs
        - -r requirements-jupyter.txt   #: Jupyter
        #- -r requirements-xrt.txt       #: XRT (ray tracing)
        - -r requirements-nexus.txt     #: NeXus
        #- -r requirements-oasys.txt     #: SHADOW & OASYS
        - -r requirements-larch.txt     #: Larch
        #- -e git+https://github.com/maurov/xraysloth.git  #: Sloth dev mode
        - -e ../                        #: Sloth dev mode (local)

#: -> run 'postBuild' script to complete install of Jupyter extensions (NOTE: automatically run on binderhub)