# -*- coding: utf-8 -*-
# Conda environment configuration for: https://github.com/maurov/xraysloth
# Target: *FULL* environment
#
## Specs
# - compatible with Binderhub at mybinder.org
# - compatible with Jupyterhub at jupyter-slurm.esrf.fr
## Included libs
# - Larch      (+ Wx)
# - SILX/PyMca (+ PyQt)
# - Jupyter    (+ plotly)
# NOTE: first install packages in apt.txt
# Usage: mamba/conda env create -f environment.yml


# OLD/DEPRECATED (-> to move elsewhere)
# - OASYS
# - GL/CL
# - XRT
#   +> Nexus
#   +> Dev tools
name: sloth
channels:
    - conda-forge
    - defaults
dependencies:
    - python==3.9  #: wxpython fails with 3.10
    - pip
    - cython
    - nodejs>=12.0.0
    - pandoc
    - numpy>=1.20
    - scipy>=1.7
    - matplotlib>=3.5
    - plotly
    - scikit-learn>=1.1.1
    #- scikit-learn-intelex  #: not used yet 
    - scikit-image
    - tomopy
    - opencv
    - sqlalchemy>=1.4
    - pandas>=1
    - h5py>=3.2
    - wxpython>=4.1  #: still not working with pip!
    - pyqt>=5.9
    - pyqtwebengine
    - qtconsole
    - psutil
    - pyyaml
    - requests
    - psycopg2-binary
    - numdifftools
    - emcee
    - pytools
    - palettable
    - openpyxl
    - pint
    - mendeleev
    - pymatgen
    - pillow>=9.4.0
    - charset-normalizer
    - pycifrw
    - xraylib
    - silx>=1.0.0
    - pymca>=5.6.5
    - py3dmol
    # EXTRA / OPTIONAL / DEPRECATED
    #- nglview  #: using py3Dmol
    #- esrf-bcu::ptpython>=3.0.16
    #- esrf-bcu::bliss >= 1.9.0  #: NOT YET USED HERE!
    #- spyder
    #- spyder-kernels
    #- pyviz::holoviz  # conda conflicts!!! :TODO:
    #- rtree  #: -> `requirements-xrt.txt` (pip fails for some unknown reason)
    #- conda-forge:dask        #: for xarray (in requirements-jupyter.txt)
    #- conda-forge:netCDF4     #: for xarray (in requirements-jupyter.txt)
    #- conda-forge:bottleneck  #: for xarray (in requirements-jupyter.txt)
    - pip:
        #- -r ../requirements.txt #: base // INSTALLED HERE VIA CONDA!!!
        - -r requirements-dev.txt #: IDE/dev tools
        - -r requirements-docs.txt #: to build docs
        - -r requirements-jupyter.txt #: Jupyter
        - -r requirements-nexus.txt #: NeXus
        #- -r requirements-xrt.txt #: XRT (ray tracing)
        #- -r requirements-oasys.txt #: SHADOW & OASYS
        - -r requirements-larch.txt #: Larch
        #- -e git+https://github.com/maurov/xraysloth.git  #: Sloth dev mode
        - -e ../                        #: Sloth dev mode (local)

#: -> run 'postBuild' script to complete install of Jupyter extensions (NOTE: automatically run on binderhub)
