# -*- coding: utf-8 -*-
# Conda environment configuration for: https://github.com/maurov/xraysloth
# Target: *FULL* environment for sloth based on
#   +> Larch (Wx)
#   +> SILX  (PyQt5)
#   +> OASYS
#   +> Jupyter
#   +> GL/CL
#   +> XRT
#   +> Nexus
#   +> Dev tools
# NOTE: first install packages in apt.txt
# Usage: mamba/conda env create -f environment.yml
name: sloth
channels:
    - defaults
    - conda-forge
dependencies:
    - python == 3.9
    - pip
    - cython
    - numpy >= 1.20
    - scipy >= 1.5
    - matplotlib >= 3.0
    - pandas >= 0.25
    - scikit-learn
    - scikit-image
    - nodejs >= 12.0.0
    - wxpython >= 4.0.4  #: still not working with pip!
    - pyqt >= 5.9
    - pyqtwebengine
    - qtconsole
    - h5py >= 2.10
    - sqlalchemy >= 1.0
    - pillow >= 8.3.2
    - psutil
    - pyyaml
    - requests
    - psycopg2-binary
    - numdifftools
    - emcee
    - pytools
    - palettable
    - openpyxl
    - pint
    - silx >= 1.0.0
    - pymca >= 5.6.5
    - xraylib
    - pymatgen
    - esrf-bcu::ptpython >= 3.0.16
    #- esrf-bcu::bliss >= 1.8.0 #NOT YET!
    #- pyviz::holoviz # conda conflicts!!! :TODO:
    - rtree  # -> `requirements-xrt.txt` (pip fails for some unknown reason)
    #- conda-forge:dask        # for xarray (in requirements-jupyter.txt)
    #- conda-forge:netCDF4     # for xarray (in requirements-jupyter.txt)
    #- conda-forge:bottleneck  # for xarray (in requirements-jupyter.txt)
    - pip:
        #- -r ../requirements.txt #: base // INSTALLED HERE VIA CONDA!!!
        - -r requirements-dev.txt #: IDE/dev tools
        - -r requirements-docs.txt #: to build docs
        - -r requirements-jupyter.txt #: Jupyter
        - -r requirements-nexus.txt #: NeXus
        #- -r requirements-xrt.txt #: XRT (ray tracing)
        #- -r requirements-oasys.txt #: SHADOW & OASYS
        - -r requirements-larch.txt #: Larch
        #- -e git+https://github.com/maurov/xraysloth.git  #: Sloth dev mode
        - -e ../                        #: Sloth dev mode (local)

#: -> run 'postBuild' script to complete install of Jupyter extensions (NOTE: automatically run on binderhub)