# -*- coding: utf-8 -*-
# Conda environment configuration for: [XRT](https://xrt.readthedocs.io/)
# Usage: conda env create -f environment-xrt.yml
name: xrt
channels:
    - defaults
dependencies:
    - python == 3.7
    - pip >= 19.2
    - spyder >= 4.0.1
    # - pyopengl-accelerate
    - conda-forge::pyopengl
    - conda-forge::freeglut
    - conda-forge::pyopencl
    - conda-forge::ocl-icd-system
    - pip:
        # - xrt >= 1.3.3
        - git+https://github.com/maurov/xrt.git
