# -*- coding: utf-8 -*-
# Conda environment configuration for: https://github.com/maurov/xraysloth (on Windows)
# Target: environment for [XRT](https://xrt.readthedocs.io/)
# Usage: conda env create -f environment-win.yml
name: py37w
channels:
    - defaults
dependencies:
    - python == 3.7
    - pip >= 19.2
    - spyder >= 4.0.1
    - pyopengl
    - pyopengl-accelerate
    - freeglut
    - conda-forge::pyopencl
    - pip:
        - xrt
