#Python environment for: https://github.com/maurov/xraysloth
#Target: base environment for sloth based on Larch (Wx) + SILX (Qt) + OASYS
#Usage: conda env create -f environment.yml
name: sloth-env
channels:
    - defaults
    #NOTE: specific channels are given per-package, not here!
dependencies:
    - python=3.6
    - pip
    - pyqt=5
    - numpy>=1.16
    - scipy>=1.2
    - matplotlib>=3.0
    - h5py>=2.10
    - sqlalchemy>=0.9
    - pandas
    - qtconsole
    - ipython
    - ipykernel
    - sphinx>=1.5
    - pyyaml
    - conda-forge::xraylib
    - conda-forge::lmfit>=0.9.13
    - GSECARS::xraylarch>=0.9.46
    - pip:
        - xraydb
        - hdf5plugin
        - silx>=0.11.0
        - pymca>=5.5.0
        - http://ftp.esrf.eu/pub/scisoft/shadow3/wheels/shadow3-18.5.30-cp36-cp36m-linux_x86_64.whl; sys_platform == 'linux'
        - resources
        - oasys-canvas-core
        - oasys-widget-core
        - oasys1
        - srxraylib
        - syned
        - wofry
        - OASYS1-ShadowOui
        - OASYS1-XOPPY
