#Python environment for: https://github.com/maurov/xraysloth
#Target: base environment for sloth based on Larch (Wx) + SILX (Qt) + OASYS + Jupyter
#Usage: conda env create -f environment.yml
name: sloth
channels:
    - defaults
dependencies:
    - python=3.7
    - pip
    - nodejs
    - pyqt=5
    - wxpython>=4.0.3
    - numpy>=1.16
    - scipy>=1.2
    - matplotlib>=3.0
    - h5py>=2.10
    - sqlalchemy>=0.9
    - pandas>=0.25
    - qtconsole
    - ipython
    - ipykernel
    - scikit-image
    - scikit-learn
    - requests
    - pandoc
    - conda-forge::xraylib
    - pip:
        #: utils
        - termcolor
        - pyyaml
        - palettable
        - peakutils>=1.3
        - asteval>=0.9
        - uncertainties>=3.1
        - pyshortcuts>=1.5
        #: Wx (-> Larch)
        - wxmplot>=0.9
        - wxutils>=0.2
        #: Build docs
        - sphinx>=1.5
        - sphinxcontrib-napoleon
        - sphinx_rtd_theme
        - recommonmark
        #: Jupyter
        - jupyterlab_server
        - jupyterlab>=1.0
        - ipywidgets>=7.5
        - notebook
        - jupyterhub
        - ipympl
        - nbsphinx
        - widgetsnbextension>=3.5.0
        #: Base (sci)libs
        - hdf5plugin>=2.1
        - xraydb>=4.3
        - lmfit>=0.9.15
        - silx>=0.11
        - pymca>=5.5.3
        #: NeXus
        - pyresttable
        - spec2nexus
        - nexusformat
        - nexpy
        #: SHADOW & OASYS
        - shadow3==18.5.30
        - resources
        - oasys-canvas-core
        - oasys-widget-core
        - oasys1
        - srxraylib
        - syned
        - wofry
        - OASYS1-ShadowOui
        - OASYS1-XOPPY
        #: From source (Larch & Sloth)
        - git+https://github.com/xraypy/xraylarch
        - git+https://github.com/maurov/xraysloth
