#Python environment for: https://github.com/maurov/xraysloth
#Target: running on mybinder.org
#Usage: automatically built
name: sloth-binder
channels:
    - defaults
dependencies:
    - python=3.6
    - pip
    - nodejs
    - pyqt=5
    - numpy>=1.16
    - scipy>=1.2
    - matplotlib>=3.0
    - h5py>=2.8
    - sqlalchemy>=0.9
    - conda-forge::xraylib
    - GSECARS::wxmplot>=0.9
    - GSECARS::wxutils>=0.2
    - pip:
        #: utils
        - termcolor
        - pyyaml
        - palettable
        - peakutils>=1.3
        - asteval>=0.9
        - uncertainties>=3.1
        - pyshortcuts>=1.4
        #: Jupyter
        - jupyterlab_server
        - jupyterlab>=1.0
        - ipywidgets>=7.5
        - jupyterhub
        - ipympl
        - widgetsnbextension
        - jupyterlab-git
        #: Base (sci)libs
        - pandas
        - xraydb
        - hdf5plugin
        - lmfit>=0.9.13
        - silx>=0.11
        - http://ftp.esrf.eu/pub/scisoft/shadow3/wheels/shadow3-18.5.30-cp36-cp36m-linux_x86_64.whl; sys_platform == 'linux'
        #: From source
        - git+https://github.com/xraypy/xraylarch
        - git+https://github.com/maurov/xraysloth
