#Python environment for: https://github.com/maurov/xraysloth
#Target: local development environment based on Jupyterlab + code editing
#Usage: conda env create -f environment-lab.yml
name: sloth-lab
channels:
    - defaults
dependencies:
    - python=3.6
    - pip
    - nodejs
    - pyqt=5
    - wxpython>=4.0.3
    - numpy>=1.16
    - scipy>=1.2
    - matplotlib>=3.0
    - h5py>=2.9
    - pandas
    - scikit-image
    - scikit-learn
    - requests
    - sqlalchemy>=0.9
    - conda-forge::xraylib
    - pip:
        #: utils
        - termcolor
        - pyyaml
        - palettable
        - peakutils>=1.3
        - asteval>=0.9
        - uncertainties>=3.1
        - pyshortcuts>=1.4
        #: Wx (-> Larch)
        - wxmplot>=0.9
        - wxutils>=0.2
        #: Python IDE tools
        - rope         #: completions and renaming
        - yapf         #: code formatting (preferred over autopep8)
        - mccabe
        - pyflakes     #: faster than pylint
        - pycodestyle  #: linter for style checking
        - flake8       #: wrapper around pyflakes, pycodestyle and mccabe
        - black
        - pydocstyle   #: linter for docstring style checking
        - doc8
        - python-language-server
        - pyls-black
        #: Build docs
        - sphinx>=1.5
        - sphinxcontrib-napoleon
        - sphinx_rtd_theme
        - recommonmark
        #: Jupyter
        - jupyterlab_server
        - jupyterlab>=1.0
        - ipywidgets>=7.5
        - jupyterhub
        - ipympl
        - nbsphinx
        - widgetsnbextension>=3.5.0
        - jupyterlab_code_formatter
        - jupyterlab-git
        - jupyterlab_latex
        #: Base (sci)libs
        - xraydb
        - hdf5plugin
        - lmfit>=0.9.13
        - silx>=0.11
        - pymca>=5.5.1
        - http://ftp.esrf.eu/pub/scisoft/shadow3/wheels/shadow3-18.5.30-cp36-cp36m-linux_x86_64.whl; sys_platform == 'linux'

#: -> run 'postBuild' script to complete install of Jupyter extensions
