#Python environment for: https://github.com/maurov/xraysloth
#Target: *FULL* environment for sloth based on Larch (Wx) + SILX (Qt) + OASYS + Jupyter + GL + XRT
#Usage: conda env create -f environment.yml
name: sloth
channels:
    - defaults
dependencies:
    - python==3.7
    - pip
    - nodejs
    #: PyOpenGL / PyOpenCL
    - pyopengl
    - conda-forge::pyopencl
    - conda-forge::pocl
    - conda-forge::oclgrind
    - conda-forge::freeglut
    #: Qt + Wx
    - pyqt>=5.9.2
    - wxpython>=4.0.4
    #: Sci-base
    - numpy>=1.16
    - scipy>=1.2
    - matplotlib>=3.0
    - h5py>=2.9
    - sqlalchemy>=1.3
    - pandas>=0.25
    - ipython>=7.10
    - ipykernel>=5.1
    - scikit-image
    - scikit-learn
    - requests
    - conda-forge::xraylib
    - conda-forge::pymca==5.5.3
    - GSECARS::xraylarch==0.9.46
    #: Docs
    - pandoc
    - sphinx>=1.8
    #: Python IDE tools (linters and formatters)
    #: [overview](http://books.agiliq.com/projects/essential-python-tools/en/latest/linters.html)
    #: [comparison](https://realpython.com/python-code-quality/)
    #: [full list](https://github.com/vintasoftware/python-linters-and-code-analysis)
    - rope         #: completions and renaming
    - pyflakes     #: linter (used by flake8, faster than pylint)
    - mccabe       #: linter (used by flake8)
    - pycodestyle  #: linter (used by flake8, for style checking)
    - flake8       #: linter (wrapper on top of +pyflakes, +pycodestyle and +mccabe)
    - pydocstyle   #: linter for docstring style checking
    - black        #: formatter (preferred over: yapf and autopep8)
    - pytest
    - nose
    #: Python IDE (mainly used by XRT)
    - spyder==4.0.0
    - pip:
        #: **ALREDY INSTALLED VIA CONDA**
        #- PyQt5 == 5.12
        #- pyqtwebengine == 5.12
        #- spyder >= 4.0.0
        #- peakutils>=1.3
        #- asteval>=0.9
        #- uncertainties>=3.1
        #- pyshortcuts>=1.5
        #- wxmplot>=0.9
        #- wxutils>=0.2
        #- termcolor
        #- pyyaml
        #- lmfit>=0.9.15
        #- hdf5plugin>=2.1
        #- silx>=0.11
        #- pymca>=5.5.3
        #: **PIP ONLY**
        #: utils
        - pytools
        - palettable
        - xlrd  #: read Excel files
        - xlwt  #: write Excel files
        - doc8         #: style checker for rst
        #: Build docs
        - sphinxcontrib-napoleon
        - sphinx_rtd_theme
        - recommonmark
        #: Jupyter
        - jupyterlab_server
        - jupyterlab>=1.0
        - ipywidgets>=7.5
        - notebook
        - jupyterhub
        - ipympl
        - nbsphinx
        - widgetsnbextension>=3.5.0
        #: Base (sci)libs
        - xraydb>=4.3
        - xrt>=1.3.3
        #: NeXus
        - pyresttable
        - spec2nexus
        - nexusformat
        - nexpy
        #: SHADOW & OASYS
        - shadow3==18.5.30
        - resources
        - oasys-canvas-core
        - oasys-widget-core
        - oasys1
        - srxraylib
        - syned
        - wofry
        - OASYS1-ShadowOui
        - OASYS1-XOPPY
        #: From source (Larch & Sloth)
        - git+https://github.com/maurov/xraysloth

#: -> run 'postBuild' script to complete install of Jupyter extensions (NOTE: automatically run on binderhub)