#!/bin/bash

# =====================
# Jupyterlab extensions
# =====================

# Script automatically run by mybinder.org / or manually on `sloth-lab`
# Packages specified in `environment.yml`

# NOTE: if required, set proxy first:
#npm config set proxy "http://domain\username:password@servername:port/"
#npm confit set proxy "http://proxy.esrf.fr:3128/"

# ------------------------
# JUPYTERLAB EXTENSION
# COMMON REQUIREMENTS FOR:
# - ipywidgets
# - jupyter-matplotlib
# - plotly
# - ipytree
# ------------------------
# Avoid "JavaScript heap out of memory" errors during extension installation
# (OS X/Linux)
export NODE_OPTIONS=--max-old-space-size=4096
jupyter labextension install @jupyter-widgets/jupyterlab-manager --no-build

# ----------
# IPYWIDGETS
# ----------
# https://ipywidgets.readthedocs.io/en/stable/user_install.html
jupyter nbextension enable --py widgetsnbextension --sys-prefix

# ------
# PLOTLY
# ------
# https://plotly.com/python/
# https://plot.ly/python/getting-started/#jupyterlab-support-python-35 
# Jupyterlab renderer support
jupyter labextension install jupyterlab-plotly --no-build
# Jupyter widgets extension (OPTIONAL)
jupyter labextension install @jupyter-widgets/jupyterlab-manager plotlywidget

# ---------------------------
# IPYMPL / JUPYTER-MATPLOTLIB
# ---------------------------
# https://github.com/matplotlib/jupyter-matplotlib
jupyter labextension install jupyter-matplotlib --no-build

# ------
# DRAWIO
# ------
# https://github.com/QuantStack/jupyterlab-drawio
jupyter labextension install jupyterlab-drawio --no-build

# ---
# TOC
# ---
# https://github.com/jupyterlab/jupyterlab-toc
jupyter labextension install @jupyterlab/toc --no-build

# -------
# IPYTREE
# -------
# https://github.com/QuantStack/ipytree
jupyter labextension install ipytree --no-build

# -------
# HOLOVIZ
# -------
# https://holoviz.org/
#jupyter labextension install @pyviz/jupyterlab_pyviz --no-build  ##fails with Jupyterlab >3

# ------------------------------------------------
# /!\ EXPERIMENTAL PACKAGES: NOT INCLUDED YET /!\
# ------------------------------------------------
# Packages specified in `environment-lab.yml`

# -----
# JUPYTERLAB-HDF5
# -----
# https://github.com/jupyterlab/jupyterlab-hdf5
# jupyter labextension install @jupyterlab/hdf5 --no-build

# -----
# LATEX
# -----
# https://github.com/jupyterlab/jupyterlab-latex
# jupyter labextension install @jupyterlab/latex --no-build

# ----------------------
# CODE FORMATTER (BLACK)
# ----------------------
# https://github.com/ryantam626/jupyterlab_code_formatter
# jupyter labextension install @ryantam626/jupyterlab_code_formatter --no-build
# jupyter serverextension enable --py jupyterlab_code_formatter

# ---
# GIT
# ---
# /!\ SECURITY ISSUE /!\ -> do not enable this extension on Binderhub !!!
# https://github.com/jupyterlab/jupyterlab-git
# jupyter labextension install @jupyterlab/git --no-build
# jupyter serverextension enable --py jupyterlab_git

# ------------
# GOOGLE-DRIVE
# ------------
# https://github.com/jupyterlab/jupyterlab-google-drive
# jupyter labextension install @jupyterlab/google-drive --no-build

# --------------------------------------------------------------------- 
# Build extensions in one run
# (must be done to activate extensions since --no-build is used above)
# --------------------------------------------------------------------- 
jupyter lab build

# Unset NODE_OPTIONS environment variable
# (OS X/Linux)
unset NODE_OPTIONS

## NPM ##
npm install -g configurable-http-proxy
